### ISSUE TITLE
Distinguere tra "modalità torneo" e "modalità riposo"

### ISSUE THREAD

**Issue by armisael** [stellamargonar/calcio_splash#11]
Sarebbe da avere due cose diverse, in base al periodo:
- il torneo è alle porte? Modalità "torneo":
  - da attivare verso aprile/maggio, quando tutto è definito;
  - l'homepage indica le info del torneo: date, luogo, etc
  - si possono vedere i regolamenti e scaricare i moduli
- il torneo di quest'anno è finito, o siamo a gennaio e ancora non è pronto? Modalità "riposo":
  - niente "Info > Regolamento" o "Info > Iscrizioni"
  - niente "Torneo" con partite e via dicendo, solo le edizioni passate
  - homepage mostra solo "wall of fame" e info generiche tipo "Il prossimo torneo sarà pronto quando sarà pronto"

Tutto governato da una settings, così:
- quando abbiamo tutto pronto la mettiamo a `True` e il nuovo torneo va live;
- quando è finito la rimettiamo a `False` e scarichiamo il sito statico.

**Comment by stellamargonar** [comment]
Per modificare modalità ora basta cambiare la settings
```
WEBSITE_MODE = "default"  # "tournament"
```
default  =  tutto l'anno
tournament = durante il torneo
