### ISSUE TITLE
Mostrare la partita in corso live

### ISSUE THREAD

**Issue by armisael** [stellamargonar/calcio_splash#12]
In "modalità torneo", mostrare:
- in homepage
- nella pagina del torneo

quale partita è in corso / sarà la prossima ad essere giocata.

Se la partita è in corso, fare polling per aggiornare live il risultato.

Se la partita è in attesa, mostrare un countdown per l'inizio della partita (che vada a zero, non che diventi negativo quando siamo in ritardo :D)

**Comment by stellamargonar** [comment]
https://github.com/stellamargonar/calcio_splash/commit/4404ac33e4f31c1cc08483ec65b79d60d1f023d3
